steps:
  # Initialize git submodules
  - name: 'gcr.io/cloud-builders/git'
    args: ['submodule', 'update', '--init', '--recursive']

  # Build API image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/jobwin/saleor-api', '.']

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/jobwin/saleor-api']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'saleor-api'
      - '--image'
      - 'gcr.io/jobwin/saleor-api'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'saleor-sql-sa@jobwin.iam.gserviceaccount.com'
      - '--set-env-vars'
      - |
        DATABASE_URL=postgresql://saleor-user:${_DB_PASSWORD}@//cloudsql/jobwin:us-central1:saleor-db/saleor,
        PROJECT_ID=jobwin,
        ALLOWED_HOSTS=*.run.app,
        DEBUG=False
      - '--add-cloudsql-instances'
      - 'jobwin:us-central1:saleor-db'

images:
  - 'gcr.io/jobwin/saleor-api'

substitutions:
  _DB_PASSWORD: ${_DB_PASSWORD}
  _REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'