steps:
  # Build API image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/jobwin/saleor-api', '.']

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/jobwin/saleor-api']

  # Get database password from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$DB_PASSWORD" > /workspace/db_password
    secretEnv: ['DB_PASSWORD']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'saleor-api'
      - '--image'
      - 'gcr.io/jobwin/saleor-api'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'saleor-sql-sa@jobwin.iam.gserviceaccount.com'
      - '--set-env-vars'
      - |
        DATABASE_URL=postgresql://saleor-user:$(cat /workspace/db_password)@//cloudsql/jobwin:us-central1:saleor-db/saleor,
        PROJECT_ID=jobwin,
        ALLOWED_HOSTS=*.run.app,
        DEBUG=False,
        GOOGLE_CLOUD_PROJECT=jobwin
      - '--cpu'
      - '1'
      - '--memory'
      - '2Gi'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8000'
      - '--timeout'
      - '300'
      - '--cpu-throttling'
      - 'false'

  # Set up Cloud SQL connection
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'saleor-api'
      - '--add-cloudsql-instances'
      - 'jobwin:us-central1:saleor-db'
      - '--region'
      - 'us-central1'

images:
  - 'gcr.io/jobwin/saleor-api'

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/jobwin/secrets/saleor-db-password/versions/latest
      env: 'DB_PASSWORD'

timeout: '1800s'