steps:
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'saleor-api'
      - '--image'
      - 'ghcr.io/saleor/saleor:3.20'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'saleor-sql-sa@jobwin.iam.gserviceaccount.com'
      - '--set-env-vars'
      - |
        DATABASE_URL=postgresql://saleor-user:${_DB_PASSWORD}@//cloudsql/jobwin:us-central1:saleor-db/saleor,
        ALLOWED_HOSTS=*.run.app,
        DEBUG=False,
        SECRET_KEY=${_SECRET_KEY}
      - '--add-cloudsql-instances'
      - 'jobwin:us-central1:saleor-db'
      - '--port'
      - '8000'
      - '--memory'
      - '1Gi'

  # Deploy Dashboard
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'saleor-dashboard'
      - '--image'
      - 'ghcr.io/saleor/saleor-dashboard:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'

substitutions:
  _DB_PASSWORD: ""
  _SECRET_KEY: ""

options:
  logging: CLOUD_LOGGING_ONLY