steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed "s/\${_DB_PASSWORD}/$_DB_PASSWORD/g; s/\${_SECRET_KEY}/$_SECRET_KEY/g" deployment.yaml > deployment_final.yaml
        gcloud run services replace deployment_final.yaml \
          --platform=managed \
          --region=us-central1 \
          --project=jobwin

substitutions:
  _DB_PASSWORD: ""
  _SECRET_KEY: ""

options:
  logging: CLOUD_LOGGING_ONLY